### ISSUE TITLE
Obstacle avoidance algorithm 

### ISSUE THREAD

**Issue by pras2020** [icboredman/cherokey_ws#1]
What obstacle avoidance algorithm was used in the code to estimate the decision from the depth image 

https://www.researchgate.net/publication/264887011_Comparative_Presentation_of_Real-Time_Obstacle_Avoidance_Algorithms_Using_Solely_Stereo_Vision

In the above article there are three methods 
1.Mean estimation method
2.Threshold estimation method
3.Multi threshold method 

please help me to understand the algorithm for obstacle avoidance in stereo vision

**Comment by icboredman** [comment]
I used [AMCL](http://wiki.ros.org/amcl), part of ROS navigation stack. Please see [my blog page](https://boredomprojects.net/index.php/projects/robot-navigation-using-stereo-vision) for more information about the project.

Sorry for a very late reply. :)
